// Vendor the DSP / BLE / focus modules from web-ble-monitor into src/lib/.
//
// nf-obs must stay independently clonable, so it carries its own copy rather than importing
// across sibling repos. The copies are BYTE-IDENTICAL on purpose: that is the only thing that
// makes drift detectable.
//
//   bun run sync:lib     — re-copy from ../web-ble-monitor
//   bun run check:lib    — fail if the copies have drifted (runs before test/build)
//
// The vendored vitest suites come along too, so a bad sync breaks the build rather than
// silently changing what the focus score means.

import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SOURCE = resolve(ROOT, '..', 'web-ble-monitor', 'src', 'lib');
const DEST = join(ROOT, 'src', 'lib');

/** Modules nf-obs needs, plus the suites that prove they still behave. */
const FILES = [
	'dsp.ts',
	'dsp.test.ts',
	'ble.ts',
	'ble.test.ts',
	'focus.ts',
	'focus.test.ts',
	'adc.ts'
] as const;

const BANNER = `// ─────────────────────────────────────────────────────────────────────────────
// VENDORED from web-ble-monitor/src/lib/ — DO NOT EDIT THIS FILE.
// Edit it in web-ble-monitor, then run \`bun run sync:lib\` here.
// \`bun run check:lib\` fails the build if this copy has drifted.
// ─────────────────────────────────────────────────────────────────────────────
`;

const check = process.argv.includes('--check');

if (!existsSync(SOURCE)) {
	// A standalone clone (which is how almost everyone gets this repo) has no upstream to
	// compare against — the vendored copies in src/lib/ ARE the source of truth there, and their
	// own test suites still run. Only refuse when someone asked us to WRITE and we have nothing
	// to write from.
	if (check) {
		console.log('· web-ble-monitor not checked out alongside — skipping the drift check.');
		process.exit(0);
	}
	console.error(
		`✗ Cannot find web-ble-monitor at ${SOURCE}\n\n` +
			`  NeuroHUD vendors its DSP from that repo. To re-sync, check the two out side by side:\n` +
			`      parent/\n` +
			`        web-ble-monitor/\n` +
			`        neurohud/\n`
	);
	process.exit(1);
}

await mkdir(DEST, { recursive: true });

const drifted: string[] = [];
const missing: string[] = [];

for (const file of FILES) {
	const upstream = await readFile(join(SOURCE, file), 'utf8');
	const vendored = BANNER + upstream;
	const target = join(DEST, file);

	if (check) {
		if (!existsSync(target)) {
			missing.push(file);
			continue;
		}
		const current = await readFile(target, 'utf8');
		if (current !== vendored) drifted.push(file);
		continue;
	}

	await writeFile(target, vendored);
	console.log(`  vendored  src/lib/${file}`);
}

if (!check) {
	console.log(`\n✓ Synced ${FILES.length} files from web-ble-monitor.`);
	process.exit(0);
}

if (missing.length || drifted.length) {
	console.error('✗ Vendored library is out of sync with web-ble-monitor.\n');
	for (const f of missing) console.error(`    missing  src/lib/${f}`);
	for (const f of drifted) console.error(`    drifted  src/lib/${f}`);
	console.error(
		`\n  These files are the source of truth for what the focus score MEANS.\n` +
			`  Run \`bun run sync:lib\` to re-vendor them.`
	);
	process.exit(1);
}

console.log(`✓ Vendored library matches web-ble-monitor (${FILES.length} files).`);
